# 数据相关配置
data:
  data_dir: '/home/bingxing2/home/scx7as9/run/CSUqx/CH/data/preprocess/processed/data'
  props_dir: '/home/bingxing2/home/scx7as9/run/CSUqx/CH/data/preprocess/processed/properties'
  split_file: '/home/bingxing2/home/scx7as9/run/CSUqx/CH/data/preprocess/splits.json'
  patch_size: [64, 128, 128]
  batch_size: 2
  num_workers: 4
  oversample_foreground_percent: 0.7

# 模型相关配置
model:
  in_channels: 1
  out_channels: 1

# 训练相关配置
training:
  num_epochs: 200
  learning_rate: 0.001
  weight_decay: 1e-5
  validate_every: 10
  save_every: 50

# 损失函数相关配置
loss:
  alpha: 0.5
  gamma: 2.0

# 日志和检查点相关配置
logging:
  log_dir: '/home/bingxing2/home/scx7as9/run/CSUqx/CH/outputs/tensorboard_logs'
  checkpoint_dir: '/home/bingxing2/home/scx7as9/run/CSUqx/CH/outputs/checkpoints'