# ===========================================================================
# 数据集配置
# ===========================================================================
data:
  data_dir: "/home/bingxing2/home/scx7as9/run/CSUqx/DataBase/Task08_HepaticVessel/imagesTr"
  label_dir: "/home/bingxing2/home/scx7as9/run/CSUqx/DataBase/Task08_HepaticVessel/labelsTr"
  preprocessed_dir: "/home/bingxing2/home/scx7as9/run/CSUqx/CH/data/frangi"
  patch_size: 64
  samples_per_volume: 3
  random_seed: 42
  train_val_split: 0.8

# ===========================================================================
# 模型配置
# ===========================================================================
model:
  input_channels: 1
  output_classes: 1

# ===========================================================================
# 训练配置
# ===========================================================================
train:
  batch_size: 2
  epochs: 200
  lr: 0.0001
  weight_decay: 0.00001
  validate_every: 5
  save_every: 20
  output_dir: "outputs"

# ===========================================================================
# 数据增强配置
# ===========================================================================
aug:
  rotation_max_angle: 15
  flip_probability: 0.5
  intensity_scale_range: [0.9, 1.1]
  intensity_shift_range: [-0.1, 0.1]
  gaussian_noise_std: 0.01