# 默认配置文件

# 数据参数
max_cases: 10
max_val_cases: 5
random_sampling: true

# 模型参数
ch_params:
  max_n: 3
  max_k: 4
  max_l: 5
  cylindrical_dims: [32, 36, 32]

# Tier特定参数
tier_params:
  0:  # 器官级别
    max_n: 2
    max_k: 3
    max_l: 4
    r_scale: 1.0
  1:  # 结构级别
    max_n: 3
    max_k: 4
    max_l: 5
    r_scale: 1.5
  2:  # 细节级别
    max_n: 4
    max_k: 5
    max_l: 6
    r_scale: 2.0

# 训练参数
vessel_weight: 10.0
tumor_weight: 15.0
use_boundary: true
weight_decay: 1e-5

# 推理参数
window_size: 64
overlap: 0.5

# 添加以下部分到配置文件

# 智能采样参数
smart_sampling:
  enabled: true
  warmup_epochs: 5
  base_tier1: 10
  base_tier2: 30
  max_tier1: 20
  max_tier2: 60
  enable_hard_mining: true
  enable_adaptive_density: true
  enable_importance_sampling: true