# =============================================================================
# 默认配置文件  （所有实验先读取此文件，再用 tier0_pretrain.yaml 等覆盖差异）
# =============================================================================

# -----------------------------------------------------------------------------
# 数据
max_cases:        2
max_val_cases:     1
random_sampling:  true

# -----------------------------------------------------------------------------
# CH-Branch 参数
ch_params:
  max_n: 3
  max_k: 4
  max_l: 5
  cylindrical_dims: [32, 36, 32]

# -----------------------------------------------------------------------------
# Tier-specific 参数
tier_params:
  0:
    max_n: 2
    max_k: 3
    max_l: 4
    r_scale: 1.0
  1:
    max_n: 3
    max_k: 4
    max_l: 5
    r_scale: 1.5
  2:
    max_n: 4
    max_k: 5
    max_l: 6
    r_scale: 2.0

# -----------------------------------------------------------------------------
# Optimizer / 训练
optimizer:                       # ← 新增
  base_lr:          1.0e-4       # 主干 LR
  kernel_lr_scale:  0.1          # EdgeEnhancement.kernels = base_lr × 0.1
  weight_decay:     1.0e-5

amp: true                        # ← 新增：是否默认开启混合精度

# -----------------------------------------------------------------------------
# 损失相关
vessel_weight: 10.0
tumor_weight:  15.0              # 如新版 loss 未用，可保留不影响
use_boundary:  true

# -----------------------------------------------------------------------------
# Spatial Branch
spatial_out_channels: 16         # 若改动 SpatialFeatureExtractor 输出通道在此同步

# -----------------------------------------------------------------------------
# Edge-Enhancement 模块                         # ← 新增（如暂不用将 use 设 false）
edge:
  use: true
  out_channels: 8

# -----------------------------------------------------------------------------
# 推理
window_size: 64
overlap:     0.5

# -----------------------------------------------------------------------------
# 智能采样
smart_sampling:
  enabled: true
  warmup_epochs: 5
  base_tier1: 10
  base_tier2: 30
  max_tier1:  20
  max_tier2:  60
  enable_hard_mining:       true
  enable_adaptive_density:  true
  enable_importance_sampling: true
