# =============================================================================
# 肝脏血管分割模型配置文件 - 重构优化版
# 删除冲突参数，统一配置格式，适配两节点分布式训练
# =============================================================================

# -----------------------------------------------------------------------------
# 数据配置
# -----------------------------------------------------------------------------
data:
  max_cases: 3             # 训练集最大案例数
  max_val_cases: 2          # 验证集最大案例数
  random_sampling: true      # 是否随机采样病例
  num_workers: 8            # 数据加载器进程数

# -----------------------------------------------------------------------------
# 模型配置
# -----------------------------------------------------------------------------
model:
  in_channels: 1             # 输入通道数
  out_channels: 1            # 输出通道数 (1=二分类)

  # CH分支参数
  ch_params:
    max_n: 3                 # 最大角谐波阶数
    max_k: 4                 # 最大径向阶数
    max_l: 5                 # 最大轴向阶数
    cylindrical_dims: [32, 36, 32]  # 柱坐标维度 [r, theta, z]

  # 不同tier的特定参数
  tier_params:
    0:  # 器官级别 (256³)
      max_n: 2
      max_k: 3
      max_l: 4
      r_scale: 1.0
    1:  # 结构级别 (96³)
      max_n: 3
      max_k: 4
      max_l: 5
      r_scale: 1.5
    2:  # 细节级别 (64³)
      max_n: 4
      max_k: 5
      max_l: 6
      r_scale: 2.0

# -----------------------------------------------------------------------------
# 损失函数配置
# -----------------------------------------------------------------------------
loss:
  num_classes: 1             # 分类数量
  vessel_weight: 10.0        # 血管类别权重
  tumor_weight: 15.0         # 肿瘤类别权重
  use_boundary: true         # 是否使用边界增强损失

# -----------------------------------------------------------------------------
# 优化器配置
# -----------------------------------------------------------------------------
optimizer:
  type: "adamw"              # 优化器类型: adamw, adam, sgd
  base_lr: 1e-4              # 基础学习率
  kernel_lr_scale: 0.1       # 边缘增强核学习率缩放
  weight_decay: 1e-5         # 权重衰减
  momentum: 0.9              # SGD动量 (仅SGD使用)

# -----------------------------------------------------------------------------
# 学习率调度器配置
# -----------------------------------------------------------------------------
lr_scheduler:
  type: "cosine"             # 调度器类型: cosine, step, plateau
  min_lr: 1e-6               # 最小学习率 (cosine)
  step_size: 30              # 步长 (step)
  gamma: 0.1                 # 衰减因子 (step)
  factor: 0.5                # 缩放因子 (plateau)
  patience: 10               # 耐心值 (plateau)

# -----------------------------------------------------------------------------
# 预处理配置
# -----------------------------------------------------------------------------
preprocessing:
  clip_percentiles: [0.5, 99.5]  # 百分位数裁剪范围
  roi_threshold: 0.8              # ROI提取阈值
  roi_percentile: 99.8            # ROI百分位数
  use_largest_cc: true            # 是否使用最大连通区域

# -----------------------------------------------------------------------------
# 智能采样配置 (统一SamplingManager格式)
# -----------------------------------------------------------------------------
smart_sampling:
  enabled: true              # 是否启用智能采样

  # 阶段控制
  start_epoch: 10            # 开始启用智能采样的epoch
  update_interval: 5         # 采样策略更新间隔
  full_strength_epoch: 25    # 完全启用所有功能的epoch

  # Tier采样数量
  tier1_samples:
    base: 10                 # 基础采样数量
    full: 20                 # 完全启用时的采样数量
  tier2_samples:
    base: 10                 # 基础采样数量
    full: 20                 # 完全启用时的采样数量

  # 采样策略权重
  importance_weight_max: 0.6      # 重要性采样最大权重
  hard_mining_weight_max: 0.4     # 硬样本挖掘最大权重

  # 硬样本跟踪
  difficulty_maps_dir: "difficulty_maps"  # 难度图存储目录
  enable_hard_mining: true                # 是否启用硬样本挖掘
  enable_adaptive_density: true           # 是否启用自适应采样密度
  enable_importance_sampling: true        # 是否启用重要性采样

# -----------------------------------------------------------------------------
# 训练配置
# -----------------------------------------------------------------------------
training:
  epochs: 20                # 总训练轮数
  batch_size: 1              # 每GPU批次大小
  val_interval: 5            # 验证间隔
  save_interval: 10          # 检查点保存间隔
  amp: true                  # 是否使用混合精度训练

  # 早停配置
  early_stopping:
    enabled: false           # 是否启用早停
    patience: 20             # 耐心值
    min_delta: 0.001         # 最小改善值

# -----------------------------------------------------------------------------
# 分布式训练配置
# -----------------------------------------------------------------------------
distributed:
  backend: "nccl"            # 分布式后端
  find_unused_parameters: true     # 查找未使用参数
  sync_bn: false             # 是否同步批归一化

  # NCCL优化
  nccl_socket_ifname: "ib0"  # 网络接口
  nccl_ib_disable: false     # 是否禁用InfiniBand

# -----------------------------------------------------------------------------
# 验证和评估配置
# -----------------------------------------------------------------------------
evaluation:
  metrics: ["dice", "iou", "precision", "recall"]  # 评估指标
  save_predictions: false    # 是否保存预测结果
  save_visualizations: false # 是否保存可视化结果

# -----------------------------------------------------------------------------
# 日志配置
# -----------------------------------------------------------------------------
logging:
  level: "INFO"              # 日志级别: DEBUG, INFO, WARNING, ERROR
  log_interval: 10           # 训练日志打印间隔
  save_model_summary: true   # 是否保存模型摘要

  # 简洁日志设置
  disable_progress_bar: false      # 是否禁用进度条
  log_only_rank_0: true           # 只在主进程记录日志
  reduce_verbose_output: true     # 减少冗余输出

# -----------------------------------------------------------------------------
# 系统配置
# -----------------------------------------------------------------------------
system:
  seed: 42                   # 随机种子
  deterministic: false       # 是否使用确定性算法
  benchmark: true            # 是否启用cudnn benchmark

  # 内存优化
  pin_memory: true           # 是否固定内存
  non_blocking: true         # 是否非阻塞传输
  memory_format: "channels_last_3d"  # 内存格式

# -----------------------------------------------------------------------------
# 开发和调试配置
# -----------------------------------------------------------------------------
debug:
  enabled: false             # 是否启用调试模式
  save_intermediate_features: false  # 是否保存中间特征
  profile_memory: false      # 是否分析内存使用
  check_nan: false           # 是否检查NaN值

  # 快速测试设置
  fast_dev_run: false        # 快速开发运行
  overfit_batches: 0         # 过拟合批次数量 (0=禁用)

# -----------------------------------------------------------------------------
# 输出配置
# -----------------------------------------------------------------------------
output:
  save_best_only: false      # 是否只保存最佳模型
  save_last: true            # 是否保存最后的模型
  save_top_k: 3              # 保存top-k模型

  # 文件命名
  model_name: "vessel_segmenter"     # 模型名称
  experiment_name: "ta_chnet_exp"    # 实验名称
  version: "v1.0"                    # 版本号