# =============================================================================
# Optimized TA-CHNet Pipeline-Parallel Training Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Data parameters
max_cases: 2
max_val_cases: 2               # Increased for more robust validation
random_sampling: true          # Random sampling for better generalization

# -----------------------------------------------------------------------------
# ROI
preprocessing:
  roi_threshold: 0.8           # 固定阈值方式
  roi_percentile: 99.5         # 百分位数方式（二选一）
  use_largest_cc: true         # 是否保留最大连通区域

# -----------------------------------------------------------------------------
# CH-Branch parameters
ch_params:
  max_n: 3                      # Maximum angular harmonic order
  max_k: 4                      # Maximum radial order
  max_l: 5                      # Maximum axial order
  cylindrical_dims: [32, 36, 32]  # Cylindrical coordinate dimensions [r, theta, z]

# -----------------------------------------------------------------------------
# Tier-specific parameters
tier_params:
  0:  # Organ level
    max_n: 2
    max_k: 3
    max_l: 4
    r_scale: 1.0
  1:  # Structure level
    max_n: 3
    max_k: 4
    max_l: 5
    r_scale: 1.5
  2:  # Detail level
    max_n: 4
    max_k: 5
    max_l: 6
    r_scale: 2.0

# -----------------------------------------------------------------------------
# Pipeline parallelism parameters (NEW)
pipeline:
  enabled: true                  # Enable pipeline parallelism
  micro_batch_size: 1            # Micro-batch size for pipeline processing
  activation_checkpointing: true  # Enable activation checkpointing to save memory
  overlap_communication: true     # Overlap computation and communication
  recompute_activation: true      # Recompute activations to save memory

  # Stage-specific parameters
  stages:
    frontend:
      device: 'cuda:0'           # Frontend processing stage
      buffer_size: 2             # Number of batches to buffer

    ch_processing:
      device: 'cuda:1'           # CH processing stage
      buffer_size: 2

    spatial_fusion:
      device: 'cuda:2'           # Spatial processing and fusion stage
      buffer_size: 2

    backend:
      device: 'cuda:3'           # Backend processing stage
      buffer_size: 2

# -----------------------------------------------------------------------------
# Optimizer parameters
optimizer:
  type: 'AdamW'                  # Changed from Adam to AdamW for better generalization
  base_lr: 2.0e-4                # Increased learning rate for pipeline training
  kernel_lr_scale: 0.1           # EdgeEnhancement.kernels learning rate scale
  weight_decay: 2.0e-5           # Slightly increased weight decay

  # Learning rate schedule (NEW)
  lr_schedule:
    type: 'cosine'               # Cosine annealing schedule
    warmup_epochs: 5             # Warmup epochs
    min_lr_factor: 0.01          # Minimum learning rate factor

# -----------------------------------------------------------------------------
# Mixed precision and memory layout
amp: true                        # Enable automatic mixed precision
amp_opt_level: 'O1'              # AMP optimization level
channels_last: true              # Use channels_last memory format
gradient_accumulation_steps: 2   # Accumulate gradients over multiple batches

# -----------------------------------------------------------------------------
# Loss function parameters
vessel_weight: 10.0              # Vessel class weight
tumor_weight: 15.0               # Tumor class weight
use_boundary: true               # Use boundary enhancement loss
focal_gamma: 2.0                 # Focal loss gamma parameter

# -----------------------------------------------------------------------------
# Spatial Branch parameters
spatial_out_channels: 16         # SpatialFeatureExtractor output channels

# -----------------------------------------------------------------------------
# Edge-Enhancement module parameters
edge:
  use: true                      # Use edge enhancement
  out_channels: 8                # Edge enhancement output channels

# -----------------------------------------------------------------------------
# Inference parameters
window_size: 64                  # Sliding window size
overlap: 0.5                     # Sliding window overlap ratio

# -----------------------------------------------------------------------------
# Smart sampling parameters
smart_sampling:
  enabled: true                  # Enable smart sampling
  warmup_epochs: 5               # Warmup epochs
  base_tier1: 10                 # Increased base Tier-1 sampling count
  base_tier2: 10                 # Increased base Tier-2 sampling count
  max_tier1: 15                  # Increased max Tier-1 sampling count
  max_tier2: 20                  # Increased max Tier-2 sampling count
  enable_hard_mining: true       # Enable hard sample mining
  enable_adaptive_density: true  # Enable adaptive sampling density
  enable_importance_sampling: true  # Enable importance sampling
  difficulty_maps_dir: "difficulty_maps"  # Difficulty map storage directory
  update_interval: 2             # Update difficulty maps every N epochs

# -----------------------------------------------------------------------------
# Evaluation parameters
evaluation:
  eval_full_interval: 5          # Full evaluation interval
  eval_quick_interval: 1         # Quick evaluation interval
  quick_samples: 2               # Quick evaluation sample count
  group_by_tier: true            # Group metrics by tier
  feature_mmap_enabled: true     # Enable feature memory mapping
  feature_mmap_dir: "eval_tier_features"
  clear_cache_interval: 3        # Cache clearing interval
  max_eval_samples: 10           # Increased max evaluation samples
  eval_batch_size: 1             # Evaluation batch size
  include_advanced_metrics: true # Include advanced metrics
  save_predictions: false        # Save predictions
  visualize_samples: 3           # Visualization sample count
  save_visualizations: false     # Save visualizations

# -----------------------------------------------------------------------------
# Training and saving parameters
training:
  epochs: 10                  # Total training epochs
  batch_size: 1                  # Batch size
  num_workers: 8                 # Increased worker count for better data loading
  val_interval: 5                # Validation interval
  save_interval: 10              # Checkpoint saving interval
  seed: 42                       # Random seed

# -----------------------------------------------------------------------------
# Device parameters
device: "cuda"                   # Compute device

# -----------------------------------------------------------------------------
# Checkpoint parameters
checkpoint:
  save_interval: 5               # Save interval
  keep_best: true                # Keep best model
  keep_last: 3                   # Keep last N checkpoints
  metric: 'dice'                 # Metric for best model
  save_optimizer: true           # Save optimizer state
  load_stage_to_gpu: true        # Load each stage directly to its assigned GPU