# =============================================================================
# 分布式训练配置文件
# =============================================================================

# -----------------------------------------------------------------------------
# 数据
max_cases:       20     # 训练集最大案例数
max_val_cases:    5     # 验证集最大案例数
random_sampling: true   # 随机采样

# -----------------------------------------------------------------------------
# CH-Branch 参数
ch_params:
  max_n: 3               # 最大角谐波阶数
  max_k: 4               # 最大径向阶数
  max_l: 5               # 最大轴向阶数
  cylindrical_dims: [32, 36, 32]  # 柱坐标维度 [r, theta, z]

# -----------------------------------------------------------------------------
# Tier-specific 参数
tier_params:
  0:  # 器官级别
    max_n: 2
    max_k: 3
    max_l: 4
    r_scale: 1.0
  1:  # 结构级别
    max_n: 3
    max_k: 4
    max_l: 5
    r_scale: 1.5
  2:  # 细节级别
    max_n: 4
    max_k: 5
    max_l: 6
    r_scale: 2.0

# -----------------------------------------------------------------------------
# 优化器参数
optimizer:
  base_lr:          2.0e-4       # 主干学习率 (分布式训练使用更大的学习率)
  kernel_lr_scale:  0.1          # EdgeEnhancement.kernels 学习率缩放
  weight_decay:     1.0e-5       # 权重衰减
  lr_schedule:                   # 学习率调度
    type: 'cosine'               # 余弦退火
    warmup_epochs: 5             # 预热轮数
    min_lr_factor: 0.01          # 最小学习率因子

# -----------------------------------------------------------------------------
# 分布式训练特定参数
distributed:
  backend: 'nccl'                # 后端类型
  init_method: 'env://'          # 初始化方法
  sync_bn: true                  # 是否使用同步批归一化
  find_unused_parameters: true   # 查找未使用参数 (解决DDP中的潜在问题)
  grad_accumulation: 4           # 梯度累积步数 (有效增大批量大小)
  gradient_as_bucket_view: true  # 梯度作为桶视图 (减少内存使用)

# -----------------------------------------------------------------------------
# 混合精度
amp: true                        # 启用自动混合精度
amp_opt_level: 'O1'              # 混合精度优化级别

# -----------------------------------------------------------------------------
# 损失相关
vessel_weight: 10.0              # 血管权重
tumor_weight:  15.0              # 肿瘤权重
use_boundary:  true              # 使用边界增强损失

# -----------------------------------------------------------------------------
# Spatial Branch
spatial_out_channels: 16         # 空间特征提取器输出通道

# -----------------------------------------------------------------------------
# Edge-Enhancement 模块
edge:
  use: true                      # 是否使用边缘增强
  out_channels: 8                # 输出通道数

# -----------------------------------------------------------------------------
# 推理
window_size: 64                  # 滑动窗口大小
overlap:     0.5                 # 重叠比例

# -----------------------------------------------------------------------------
# 智能采样
smart_sampling:
  enabled: true                     # 启用智能采样
  warmup_epochs: 5                  # 预热轮数
  base_tier1: 10                    # Tier-1基础采样数量
  base_tier2: 30                    # Tier-2基础采样数量
  max_tier1:  20                    # Tier-1最大采样数量
  max_tier2:  60                    # Tier-2最大采样数量
  enable_hard_mining:       true    # 启用硬样本挖掘
  enable_adaptive_density:  true    # 启用自适应采样密度
  enable_importance_sampling: true  # 启用重要性采样

# -----------------------------------------------------------------------------
# 检查点
checkpoint:
  save_interval: 5             # 保存间隔（轮数）
  keep_best: true              # 保留最佳模型
  keep_last: 3                 # 保留最近的N个检查点
  metric: 'dice'               # 用于保存最佳模型的指标

# -----------------------------------------------------------------------------
# 日志和可视化
logging:
  log_interval: 10             # 日志记录间隔（批次）
  tensorboard: true            # 启用TensorBoard
  visualize_interval: 100      # 可视化间隔（批次）
  sample_images: 4             # 可视化样本数量